server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers, RETAIN_UNIQUE
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - Authentication
        - id: admin-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - Authentication
        - id: auth-oauth2
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**,/login/oauth2/**
          filters:
            - Authentication
        - id: resume-service
          uri: lb://RESUME-SERVICE
          predicates:
            - Path=/api/v1/resumes/**
          filters:
            - Authentication
        - id: section-service
          uri: lb://SECTION-SERVICE
          predicates:
            - Path=/api/v1/sections/**
          filters:
            - Authentication
        - id: template-service
          uri: lb://TEMPLATE-SERVICE
          predicates:
            - Path=/api/v1/templates/**
          filters:
            - Authentication
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - Authentication
        - id: export-service
          uri: lb://EXPORT-SERVICE
          predicates:
            - Path=/api/v1/exports/**
          filters:
            - Authentication
        - id: jobmatch-service
          uri: lb://JOBMATCH-SERVICE
          predicates:
            - Path=/api/v1/job-matches/**
          filters:
            - Authentication
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - Authentication
        - id: subscription-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/subscription/**
          filters:
            - Authentication
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG