server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - Authentication
        - id: admin-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - Authentication
        - id: auth-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**,/login/oauth2/**
          filters:
            - Authentication
        - id: resume-service
          uri: lb://resume-service
          predicates:
            - Path=/api/v1/resumes/**
          filters:
            - Authentication
        - id: section-service
          uri: lb://section-service
          predicates:
            - Path=/api/v1/sections/**
          filters:
            - Authentication
        - id: template-service
          uri: lb://template-service
          predicates:
            - Path=/api/v1/templates/**
          filters:
            - Authentication
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - Authentication
        - id: export-service
          uri: lb://export-service
          predicates:
            - Path=/api/v1/exports/**
          filters:
            - Authentication
        - id: jobmatch-service
          uri: lb://jobmatch-service
          predicates:
            - Path=/api/v1/job-matches/**
          filters:
            - Authentication
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - Authentication

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
