DELETE FROM resume_templates WHERE slug IN ('modern-executive','clean-slate','creative-canvas','academic-scholar','fresh-start');

INSERT INTO resume_templates
  (template_id, slug, name, description, category, is_premium, is_active, usage_count, version,
   thumbnail_url, tags, customization_schema, print_css,
   html_layout, css_styles, created_at, updated_at)
VALUES

-- ── 1. Modern Executive (Professional, Free) ────────────────────────────────
(UUID(), 'modern-executive', 'Modern Executive',
 'A sleek two-column professional template perfect for senior roles.',
 'Professional', 0, 1, 0, 1,
 'https://placehold.co/400x560/1e293b/ffffff?text=Modern+Executive',
 'professional,ats-friendly,two-column',
 '{"accentColor":"#2563eb","fontFamily":"Inter","fontSize":"medium"}',
 '@page{size:A4;margin:10mm} body{-webkit-print-color-adjust:exact}',
 '<div class="resume"><div class="left-col"><div class="header-block"><h1>{{fullName}}</h1><p class="job-title">{{jobTitle}}</p><div class="contact-list"><span>{{email}}</span><span>{{phone}}</span><span>{{location}}</span></div></div><div class="section"><h2>Skills</h2><ul class="skills-list">{{#skills}}<li>{{name}}</li>{{/skills}}</ul></div><div class="section"><h2>Languages</h2><ul class="skills-list">{{#languages}}<li>{{language}} <span class="level">{{proficiency}}</span></li>{{/languages}}</ul></div></div><div class="right-col"><div class="section"><h2>Summary</h2><p class="summary-text">{{summary}}</p></div><div class="section"><h2>Experience</h2>{{#experience}}<div class="entry"><div class="entry-header"><span class="entry-title">{{jobTitle}}</span><span class="entry-date">{{startDate}} – {{endDate}}</span></div><span class="entry-sub">{{company}}, {{location}}</span><p class="entry-body">{{description}}</p></div>{{/experience}}</div><div class="section"><h2>Education</h2>{{#education}}<div class="entry"><div class="entry-header"><span class="entry-title">{{degree}}</span><span class="entry-date">{{year}}</span></div><span class="entry-sub">{{institution}}</span></div>{{/education}}</div></div></div>',
 ':root{--accent:#2563eb;--font-family:"Inter",sans-serif;--text:#1e293b;--muted:#64748b;--bg-left:#1e293b;--bg-right:#ffffff}*{box-sizing:border-box;margin:0;padding:0}body{font-family:var(--font-family);color:var(--text);font-size:13px;line-height:1.6}.resume{display:flex;min-height:100vh}.left-col{width:33%;background:var(--bg-left);color:#e2e8f0;padding:28px 20px}.right-col{width:67%;background:var(--bg-right);padding:28px 24px}h1{font-size:1.6rem;font-weight:700;color:#fff;line-height:1.2}.job-title{color:var(--accent);font-weight:500;margin:4px 0 12px;font-size:.95rem}.contact-list{display:flex;flex-direction:column;gap:4px;font-size:.8rem;color:#94a3b8}.left-col .section{margin-top:24px}.left-col h2{color:#94a3b8;font-size:.7rem;text-transform:uppercase;letter-spacing:1.5px;border-bottom:1px solid #334155;padding-bottom:6px;margin-bottom:10px}.skills-list{list-style:none;display:flex;flex-direction:column;gap:6px}.skills-list li{background:#334155;border-radius:4px;padding:4px 10px;font-size:.82rem}.right-col .section{margin-bottom:20px}.right-col h2{font-size:.72rem;text-transform:uppercase;letter-spacing:1.5px;color:var(--accent);border-bottom:2px solid var(--accent);padding-bottom:5px;margin-bottom:12px}.summary-text{color:var(--muted);line-height:1.7}.entry{margin-bottom:14px}.entry-header{display:flex;justify-content:space-between;align-items:baseline}.entry-title{font-weight:600;font-size:.9rem}.entry-date{font-size:.78rem;color:var(--muted)}.entry-sub{font-size:.82rem;color:var(--accent);font-style:italic}.entry-body{margin-top:4px;color:var(--muted);font-size:.85rem}',
 NOW(), NOW()),

-- ── 2. Clean Slate (Minimalist, Free) ───────────────────────────────────────
(UUID(), 'clean-slate', 'Clean Slate',
 'Ultra-minimalist single-column layout. ATS-optimised, zero clutter.',
 'Minimalist', 0, 1, 0, 1,
 'https://placehold.co/400x560/16a34a/ffffff?text=Clean+Slate',
 'minimalist,ats-friendly,single-column',
 '{"accentColor":"#16a34a","fontFamily":"Inter","fontSize":"medium"}',
 '@page{size:A4;margin:10mm} body{-webkit-print-color-adjust:exact}',
 '<div class="resume"><div class="top-bar"></div><div class="header"><h1>{{fullName}}</h1><p class="tagline">{{jobTitle}}</p><div class="contacts"><span>{{email}}</span><span>|</span><span>{{phone}}</span><span>|</span><span>{{location}}</span></div></div><div class="body"><div class="section"><h2>Professional Summary</h2><p>{{summary}}</p></div><div class="section"><h2>Work Experience</h2>{{#experience}}<div class="entry"><div class="row"><strong>{{jobTitle}}</strong><em>{{startDate}} – {{endDate}}</em></div><div class="company">{{company}}</div><p class="desc">{{description}}</p></div>{{/experience}}</div><div class="section"><h2>Education</h2>{{#education}}<div class="entry"><div class="row"><strong>{{degree}}</strong><em>{{year}}</em></div><div class="company">{{institution}}</div></div>{{/education}}</div><div class="section skills-section"><h2>Core Skills</h2><div class="skills-wrap">{{#skills}}<span class="skill-tag">{{name}}</span>{{/skills}}</div></div></div></div>',
 ':root{--accent:#16a34a;--font-family:"Inter",sans-serif}*{box-sizing:border-box;margin:0;padding:0}body{font-family:var(--font-family);color:#1a1a1a;font-size:13.5px;line-height:1.65;background:#fff}.resume{max-width:800px;margin:0 auto}.top-bar{height:6px;background:var(--accent)}.header{text-align:center;padding:28px 40px 18px}h1{font-size:2rem;font-weight:700;letter-spacing:-0.5px}.tagline{color:var(--accent);font-size:.95rem;margin:4px 0 10px;font-weight:500}.contacts{font-size:.82rem;color:#555;display:flex;justify-content:center;gap:8px}.body{padding:8px 40px 40px}.section{margin-bottom:20px}h2{font-size:.75rem;text-transform:uppercase;letter-spacing:2px;color:var(--accent);margin-bottom:8px;padding-bottom:4px;border-bottom:1px solid #e5e7eb}.entry{margin-bottom:12px}.row{display:flex;justify-content:space-between}.row strong{font-size:.9rem}.row em{font-size:.8rem;color:#6b7280;font-style:normal}.company{font-size:.82rem;color:#6b7280;margin:2px 0}.desc{color:#374151;font-size:.85rem;margin-top:4px}.skills-wrap{display:flex;flex-wrap:wrap;gap:8px}.skill-tag{background:#f0fdf4;border:1px solid #bbf7d0;color:#16a34a;padding:3px 10px;border-radius:999px;font-size:.8rem}',
 NOW(), NOW()),

-- ── 3. Creative Canvas (Creative, Premium) ──────────────────────────────────
(UUID(), 'creative-canvas', 'Creative Canvas',
 'Bold sidebar accent with vibrant colours. Built for designers and creatives.',
 'Creative', 1, 1, 0, 1,
 'https://placehold.co/400x560/7c3aed/ffffff?text=Creative+Canvas',
 'creative,design,sidebar,premium',
 '{"accentColor":"#7c3aed","fontFamily":"Inter","fontSize":"medium"}',
 '@page{size:A4;margin:10mm} body{-webkit-print-color-adjust:exact}',
 '<div class="resume"><div class="sidebar"><div class="avatar-wrap"><div class="avatar">{{initials}}</div></div><div class="name-block"><h1>{{fullName}}</h1><p class="role">{{jobTitle}}</p></div><div class="side-section"><h3>Contact</h3><p>{{email}}</p><p>{{phone}}</p><p>{{location}}</p></div><div class="side-section"><h3>Skills</h3>{{#skills}}<div class="skill-bar"><span class="skill-name">{{name}}</span></div>{{/skills}}</div><div class="side-section"><h3>Languages</h3>{{#languages}}<p>{{language}}</p>{{/languages}}</div></div><div class="main"><div class="main-section"><h2><span class="dot"></span>About Me</h2><p class="about">{{summary}}</p></div><div class="main-section"><h2><span class="dot"></span>Experience</h2>{{#experience}}<div class="card"><div class="card-head"><span class="ctitle">{{jobTitle}}</span><span class="cbadge">{{startDate}} – {{endDate}}</span></div><p class="csub">{{company}}</p><p class="cdesc">{{description}}</p></div>{{/experience}}</div><div class="main-section"><h2><span class="dot"></span>Education</h2>{{#education}}<div class="card"><div class="card-head"><span class="ctitle">{{degree}}</span><span class="cbadge">{{year}}</span></div><p class="csub">{{institution}}</p></div>{{/education}}</div></div></div>',
 ':root{--accent:#7c3aed;--accent2:#a78bfa;--font-family:"Inter",sans-serif}*{box-sizing:border-box;margin:0;padding:0}body{font-family:var(--font-family);font-size:13px;line-height:1.6;background:#fff}.resume{display:flex;min-height:100vh}.sidebar{width:30%;background:linear-gradient(160deg,#7c3aed,#4f46e5);color:#fff;padding:32px 20px;display:flex;flex-direction:column;gap:24px}.avatar-wrap{display:flex;justify-content:center}.avatar{width:80px;height:80px;border-radius:50%;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:1.8rem;font-weight:700;border:3px solid rgba(255,255,255,.4)}h1{font-size:1.2rem;font-weight:700;text-align:center;margin-top:8px}.role{font-size:.82rem;color:var(--accent2);text-align:center;margin-top:2px}.side-section h3{font-size:.65rem;text-transform:uppercase;letter-spacing:2px;color:var(--accent2);margin-bottom:8px;border-bottom:1px solid rgba(255,255,255,.2);padding-bottom:4px}.side-section p{font-size:.8rem;margin-bottom:4px;color:rgba(255,255,255,.85)}.skill-name{font-size:.82rem;color:rgba(255,255,255,.9)}.main{width:70%;padding:28px}h2{font-size:.72rem;text-transform:uppercase;letter-spacing:2px;color:var(--accent);margin-bottom:14px;display:flex;align-items:center;gap:8px}.dot{width:8px;height:8px;border-radius:50%;background:var(--accent);display:inline-block}.main-section{margin-bottom:22px}.about{color:#475569;font-size:.88rem;line-height:1.7}.card{background:#f8f7ff;border-left:3px solid var(--accent);padding:10px 14px;border-radius:0 8px 8px 0;margin-bottom:10px}.card-head{display:flex;justify-content:space-between;align-items:center}.ctitle{font-weight:600;font-size:.9rem;color:#1e1b4b}.cbadge{background:var(--accent);color:#fff;font-size:.72rem;padding:2px 8px;border-radius:999px}.csub{font-size:.8rem;color:var(--accent);margin:2px 0}.cdesc{font-size:.83rem;color:#475569;margin-top:4px}',
 NOW(), NOW()),

-- ── 4. Academic Scholar (Academic, Free) ────────────────────────────────────
(UUID(), 'academic-scholar', 'Academic Scholar',
 'Traditional serif layout ideal for research, academia, and graduate roles.',
 'Academic', 0, 1, 0, 1,
 'https://placehold.co/400x560/7f1d1d/ffffff?text=Academic+Scholar',
 'academic,research,serif,formal',
 '{"accentColor":"#7f1d1d","fontFamily":"Georgia","fontSize":"medium"}',
 '@page{size:A4;margin:10mm} body{-webkit-print-color-adjust:exact}',
 '<div class="resume"><div class="header"><h1>{{fullName}}</h1><p class="title-line">{{jobTitle}}</p><div class="contact-row"><span>{{email}}</span><span>{{phone}}</span><span>{{location}}</span></div><hr class="divider"></div><div class="body"><section><h2>Research Objective / Summary</h2><p class="para">{{summary}}</p></section><section><h2>Academic &amp; Work Experience</h2>{{#experience}}<div class="acad-entry"><div class="acad-row"><span class="acad-title">{{jobTitle}}</span><span class="acad-date">{{startDate}} – {{endDate}}</span></div><em class="acad-inst">{{company}}</em><p class="para">{{description}}</p></div>{{/experience}}</section><section><h2>Education</h2>{{#education}}<div class="acad-entry"><div class="acad-row"><span class="acad-title">{{degree}}</span><span class="acad-date">{{year}}</span></div><em class="acad-inst">{{institution}}</em></div>{{/education}}</section><section><h2>Publications &amp; Projects</h2>{{#projects}}<div class="pub-entry"><strong>{{name}}</strong> — <span class="para">{{description}}</span></div>{{/projects}}</section><section><h2>Competencies &amp; Skills</h2><div class="skills-row">{{#skills}}<span class="acad-skill">{{name}}</span>{{/skills}}</div></section></div></div>',
 ':root{--accent:#7f1d1d;--font-family:"Georgia",serif}*{box-sizing:border-box;margin:0;padding:0}body{font-family:var(--font-family);color:#1c1c1c;font-size:13.5px;line-height:1.7;background:#fff}.resume{max-width:780px;margin:0 auto;padding:40px}.header{text-align:center;margin-bottom:20px}h1{font-size:1.8rem;font-weight:700;letter-spacing:.5px;color:#111}.title-line{color:var(--accent);font-size:.95rem;margin:4px 0 8px;font-style:italic}.contact-row{display:flex;justify-content:center;gap:16px;font-size:.82rem;color:#555}.divider{margin:16px 0;border:none;border-top:2px solid var(--accent)}.body section{margin-bottom:20px}h2{font-size:.85rem;font-variant:small-caps;letter-spacing:1px;color:var(--accent);border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin-bottom:10px}.para{color:#374151;font-size:.88rem}.acad-entry{margin-bottom:12px}.acad-row{display:flex;justify-content:space-between}.acad-title{font-weight:700;font-size:.9rem}.acad-date{font-size:.8rem;color:#6b7280}.acad-inst{font-size:.85rem;color:var(--accent)}.pub-entry{margin-bottom:8px;font-size:.87rem}.skills-row{display:flex;flex-wrap:wrap;gap:8px}.acad-skill{border:1px solid var(--accent);color:var(--accent);padding:2px 10px;border-radius:3px;font-size:.8rem}',
 NOW(), NOW()),

-- ── 5. Fresh Start (Entry Level, Free) ──────────────────────────────────────
(UUID(), 'fresh-start', 'Fresh Start',
 'Friendly, clean layout designed for students and new graduates.',
 'Entry Level', 0, 1, 0, 1,
 'https://placehold.co/400x560/0891b2/ffffff?text=Fresh+Start',
 'entry-level,student,graduate,clean',
 '{"accentColor":"#0891b2","fontFamily":"Inter","fontSize":"medium"}',
 '@page{size:A4;margin:10mm} body{-webkit-print-color-adjust:exact}',
 '<div class="resume"><div class="header"><div class="name-block"><h1>{{fullName}}</h1><p class="sub">{{jobTitle}}</p></div><div class="contact-block"><p>{{email}}</p><p>{{phone}}</p><p>{{location}}</p></div></div><div class="body"><div class="section"><h2>About Me</h2><p class="about">{{summary}}</p></div><div class="section"><h2>Education</h2>{{#education}}<div class="entry"><div class="erow"><span class="etitle">{{degree}}</span><span class="edate">{{year}}</span></div><span class="esub">{{institution}}</span></div>{{/education}}</div><div class="section"><h2>Experience &amp; Internships</h2>{{#experience}}<div class="entry"><div class="erow"><span class="etitle">{{jobTitle}}</span><span class="edate">{{startDate}} – {{endDate}}</span></div><span class="esub">{{company}}</span><p class="edesc">{{description}}</p></div>{{/experience}}</div><div class="two-col"><div class="section"><h2>Skills</h2>{{#skills}}<div class="skill-chip">{{name}}</div>{{/skills}}</div><div class="section"><h2>Certifications</h2>{{#certifications}}<div class="cert"><strong>{{name}}</strong><span class="esub"> — {{issuer}}</span></div>{{/certifications}}</div></div></div></div>',
 ':root{--accent:#0891b2;--font-family:"Inter",sans-serif}*{box-sizing:border-box;margin:0;padding:0}body{font-family:var(--font-family);font-size:13px;line-height:1.65;background:#fff;color:#1e293b}.resume{max-width:800px;margin:0 auto}.header{background:var(--accent);color:#fff;padding:28px 32px;display:flex;justify-content:space-between;align-items:center}h1{font-size:1.7rem;font-weight:700}.sub{font-size:.9rem;opacity:.9;margin-top:4px}.contact-block{text-align:right;font-size:.82rem;opacity:.9;line-height:1.8}.body{padding:24px 32px}.section{margin-bottom:18px}h2{font-size:.72rem;text-transform:uppercase;letter-spacing:2px;color:var(--accent);margin-bottom:10px;padding-bottom:4px;border-bottom:2px solid #e0f2fe}.about{color:#475569;font-size:.88rem}.entry{margin-bottom:12px}.erow{display:flex;justify-content:space-between}.etitle{font-weight:600;font-size:.9rem}.edate{font-size:.78rem;color:#64748b}.esub{font-size:.8rem;color:var(--accent)}.edesc{font-size:.83rem;color:#475569;margin-top:3px}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:20px}.skill-chip{display:inline-block;background:#e0f2fe;color:var(--accent);padding:3px 10px;border-radius:4px;font-size:.8rem;margin:3px 3px 0 0}.cert{margin-bottom:6px;font-size:.85rem}',
 NOW(), NOW());

