spring.application.name=resumeai-web
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8089

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Feign
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

eureka.instance.prefer-ip-address=true
